#pragma once

#define CP_SHIFT_JIS 932

#define LCID_ENGLISH MAKELCID(MAKELANGID(LANG_ENGLISH, SUBLANG_DEFAULT), SORT_DEFAULT)
#define LCID_JAPANESE MAKELCID(MAKELANGID(LANG_JAPANESE, SUBLANG_DEFAULT), SORT_DEFAULT)